version: '3.8'
services:
  front:
    container_name: Frontend
    build:
      context: ./Frontend
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - blogTelematica
    volumes:
      - ./Frontend:/usr/src/app
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  back:
    container_name: Backend
    build:
      context: ./Backend
    ports:
      - "3001:3001"
    links:
      - db
    depends_on:
      - db
      - front
    networks:
      - blogTelematica
    volumes:
      - ./Backend:/usr/src/app
    command: npm run start:dev
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '123'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M


volumes:
  my-db:

networks:
  blogTelematica:
    driver: bridge
